
\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename femlisp.info
@setcontentsaftertitlepage
@settitle Femlisp User Manual
@afourpaper
@setchapternewpage odd
@c only one concept index
@syncodeindex vr cp
@syncodeindex fn cp
@syncodeindex tp cp
@c %**end of header

@macro femlisp{}
@sc{Femlisp}
@end macro

@macro CL{}
Common Lisp
@end macro

@alias module = code
@alias package = code
@alias arg = var
@alias function = code
@alias func = code
@alias mac = code
@alias symbol = code
@alias class = symbol
@alias type = symbol
@alias slot = symbol
@alias path = file
@alias program = file

@macro slisp{code}
@lisp
\code\
@end lisp
@end macro

@set EDITION 0.7
@set VERSION 0.9.10
@set UPDATED 10 March 2010

@c for install-info
@dircategory Math
@direntry
* femlisp: (femlisp).           Femlisp
@end direntry

@ifinfo
@femlisp{} User Manual @value{EDITION} (documenting @femlisp{}
@value{VERSION})

Copyright @copyright{} 2006 Nicolas Neuss, University of Karlsruhe.
@end ifinfo

@copying
This is Version @value{EDITION} of the @femlisp{} manual, last updated
@value{UPDATED}, for @femlisp{} @value{VERSION}.

Copyright @copyright{} 2005-2010 Nicolas Neuss.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
@end quotation
@end copying

@titlepage
@sp 10
@title @femlisp{} User Manual @value{EDITION}
@subtitle @femlisp{} Version @value{VERSION}
@subtitle @value{UPDATED}
@author Nicolas Neuss

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Does not work at the beginning?!
@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Femlisp

@femlisp{} is a Common Lisp toolbox for solving partial differential
equations.

@insertcopying
@end ifnottex

@menu
* Introduction::                
* Installation::                
* First steps::                 
* Programming techniques::      
* Overview::                    
* FAQ::                         
* Reference manual::            
* Copyright::                   
* Bibliography::                
* Concept Index::               

@detailmenu
 --- The Detailed Node Listing ---

Introduction, Installation, Top, Top

* Tools for solving PDEs::      
* Common Lisp::                 
* Advantages::                  

Installation

* Software needed::             
* Quick installation ::         
* Detailed installation::       

Quick installation

* Debian GNU/Linux::            
* Mac OS X::                    
* Windows/Cygwin::              

Detailed installation

* Obtaining Femlisp::           
* Installation of a CL implementation::  
* Graphics::                    
* Direct solvers::              
* Triangle mesh generator::     
* Installation of ASDF and Infix::  
* Configuration of the startup script::  
* Compiling Femlisp::           
* Setup of an interactive environment::  
* Emacs configuration::         

First steps

* Demos::                       
* Solving problems::            
* Plotting::                    
* Common Lisp environment::     
* Learning Common Lisp::        

Solving problems

* Stationary diffusion problem::  
* Nonlinear diffusion problem::  
* Elasticity problem::          
* Navier-Stokes problem::       
* Heat equation::               
* Eigenvalue problems::         

Programming techniques

* Object-oriented programming::  
* Dynamic class generation::    
* Memoization::                 
* Blackboards::                 
* Documentation::               

Overview

* Features::                    
* Structure::                   

FAQ

* Installation and Getting Started::  
* Mesh Management::             
* Linear Algebra::              
* Problems::                    
* Discretization::              
* Solvers::                     
* Parallelization::             
* General::                     

Reference manual

* Package FL.UTILITIES::        
* Package FL.MACROS::           
* Package FL.DEBUG::            
* Package FL.DEMO::             
* Package FL.TESTS::            
* Package FL.PORT::             
* Package FL.AMOP::             
* Package FL.ALIEN::            
* Package FL.MULTIPROCESSING::  
* Package FL.MATLISP::          
* Package FL.FUNCTION::         
* Package FL.MESH::             
* Package FL.PROBLEM::          
* Package FL.CDR::              
* Package FL.ELLSYS::           
* Package FL.ELASTICITY::       
* Package FL.NAVIER-STOKES::    
* Package FL.DISCRETIZATION::   
* Package FL.ELLSYS-FE::        
* Package FL.ELASTICITY-FE::    
* Package FL.NAVIER-STOKES-FE::  
* Package FL.ITERATION::        
* Package FL.MULTIGRID::        
* Package FL.GEOMG::            
* Package FL.STRATEGY::         
* Package FL.GRAPHIC::          
* Package FL.PLOT::             
* Package FL.DOMAINS::          
* Package FL.APPLICATION::      

@end detailmenu
@end menu

@include introduction.texinfo
@include installation.texinfo
@include starter.texinfo
@include programming-techniques.texinfo
@include overview.texinfo
@include FAQ.texinfo
@include reference-manual.texinfo
@include copyright.texinfo
@include bibliography.texinfo
@include indices.texinfo

@bye
