
\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename femlisp.info
@setcontentsaftertitlepage
@settitle Femlisp User Manual
@afourpaper
@setchapternewpage odd
@c only one concept index
@syncodeindex vr cp
@syncodeindex fn cp
@syncodeindex tp cp
@c %**end of header

@macro femlisp{}
@sc{Femlisp}
@end macro

@macro CL{}
Common Lisp
@end macro

@alias module = code
@alias package = code
@alias arg = var
@alias function = code
@alias func = code
@alias mac = code
@alias symbol = code
@alias class = code
@alias type = code
@alias slot = code
@alias path = file
@alias program = file
@alias library = code

@macro myanchor{title}
@anchor{\title\}\title\
@end macro

@macro slisp{code}

@lisp
\code\
@end lisp
@end macro

@set EDITION 2.0.1
@set VERSION 2.0.1
@set UPDATED 30 January 2017

@c for install-info
@dircategory Math
@direntry
* femlisp: (femlisp).           Femlisp
@end direntry

@ifinfo
@femlisp{} User Manual @value{EDITION} (documenting @femlisp{}
@value{VERSION})

Copyright @copyright{} 2006 Nicolas Neuss, University of Karlsruhe.
Copyright @copyright{} 2011- Nicolas Neuss, University of Erlangen-Nuremberg.
@end ifinfo

@copying
This is Version @value{EDITION} of the @femlisp{} manual, last updated
@value{UPDATED}, for @femlisp{} @value{VERSION}.

Copyright @copyright{} 2005- Nicolas Neuss.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
@end quotation
@end copying

@titlepage
@sp 10
@title @femlisp{} User Manual @value{EDITION}
@subtitle @femlisp{} Version @value{VERSION}
@subtitle @value{UPDATED}
@author Nicolas Neuss

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Does not work at the beginning?!
@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Femlisp

@femlisp{} is a Common Lisp toolbox for solving partial differential
equations.

@insertcopying
@end ifnottex

@menu
* Introduction::                
* Installation::                
* First steps::                 
* Programming techniques::      
* Overview::                    
* FAQ::                         
* Reference manual::            
* Copyright::                   
* Bibliography::                
* Concept Index::               

@detailmenu
 --- The Detailed Node Listing ---

Introduction, Installation, Top, Top

* Tools for solving PDEs::
* Common Lisp::
* Advantages::

Installation

* Software needed::
* Installation instructions::

Software needed

* Common Lisp implementation::
* Graphics software::
* Numerical software::
* Common Lisp libraries::

Installation instructions

* SBCL installation::
* Quicklisp::
* Simple Femlisp installation::
* Graphic programs::
* Additional numerical software::
* Advanced Femlisp installation::
* Notes for Mac OS X and Windows::

Additional numerical software

* BLAS/LAPACK libraries::
* Direct sparse solvers::
* Mesh generators::
* MPI::

Advanced Femlisp installation

* Downloading Femlisp::
* Configuring Femlisp::
* Getting CL libraries::
* Registering Femlisp::
* Compiling Femlisp::
* Starting Femlisp::

Notes for Mac OS X and Windows

* Notes for Mac OS X::
* Notes for Windows::

First steps

* Demos::
* Solving problems::
* Plotting::
* Common Lisp environment::
* Learning Common Lisp::

Solving problems

* Stationary diffusion problem::
* Nonlinear diffusion problem::
* Elasticity problem::
* Navier-Stokes problem::
* Heat equation::
* Eigenvalue problems::

Programming techniques

* Object-oriented programming::
* Dynamic class generation::
* Memoization::
* Blackboards::
* Documentation::
* Parallelization::

Parallelization

* Shared-memory parallelization::
* Distributed-memory parallelization::

Shared-memory parallelization

* Allocating a new kernel::
* Working in parallel::
* Terminating a kernel::

Distributed-memory parallelization

* Distributed objects::
* Synchronization::
* Compiling the MPI worker::
* Starting the worker pool::
* Connecting to the worker pool::
* Communicating with the worker pool::

Overview

* Features::
* Structure::

FAQ

* Installation and Getting Started FAQ::
* Mesh Management FAQ::
* Linear Algebra FAQ::
* Problems FAQ::
* Discretization FAQ::
* Solver FAQ::
* Parallelization FAQ::
* General::

Reference manual

* Package FL.UTILITIES::
* Package FL.MACROS::
* Package FL.DEBUG::
* Package FL.DEMO::
* Package FL.TESTS::
* Package FL.PORT::
* Package FL.AMOP::
* Package FL.ALIEN::
* Package FL.PARALLEL::
* Package FL.MATLISP::
* Package FL.FUNCTION::
* Package FL.MESH::
* Package FL.PROBLEM::
* Package FL.CDR::
* Package FL.ELLSYS::
* Package FL.ELASTICITY::
* Package FL.NAVIER-STOKES::
* Package FL.DISCRETIZATION::
* Package FL.ELLSYS-FE::
* Package FL.ELASTICITY-FE::
* Package FL.NAVIER-STOKES-FE::
* Package FL.ITERATION::
* Package FL.MULTIGRID::
* Package FL.GEOMG::
* Package FL.STRATEGY::
* Package FL.GRAPHIC::
* Package FL.PLOT::
* Package FL.DOMAINS::
* Package FL.APPLICATION::
* Package DDO::
* Package FEMLISP-DDO::

@end detailmenu
@end menu

@include introduction.texinfo
@include installation.texinfo
@include starter.texinfo
@include programming-techniques.texinfo
@include overview.texinfo
@include FAQ.texinfo
@include reference-manual.texinfo
@include copyright.texinfo
@include bibliography.texinfo
@include indices.texinfo

@bye
