@node Installation, First steps, Introduction, Top
@chapter Installation

@menu
* Software needed::             
* Quick installation ::         
* Detailed installation::       
@end menu

@node Software needed, Quick installation , Installation, Installation
@section Software needed

@itemize
@item A Common Lisp implementation which conforms to the ANSI standard.
@femlisp{} is known to work with CMU CL and SBCL.  However, it should be
easy to port it to other ANSI Common Lisp implementations as well.

@item Some Common Lisp software, namely:
@itemize
@item MK-DEFSYSTEM or ASDF.  Your CL implementation will probably
support one of those already.
@item Mark Kantrowitz' INFIX library.
@end itemize

@item A Common Lisp environment.  For CMUCL and SBCL I recommend Emacs
and SLIME.  Emacs/Ilisp or CMUCL/Hemlock would be alternatives, however
both Ilisp and Hemlock seem to be not actively maintained anymore.

@item Graphics software.  If you want to have graphics available, you
should have installed the following packages in such a way that they are
found in your current path.
@itemize
@item Data Explorer (OpenDX)
@item Gnuplot
@end itemize

@item Numerical software.  Although @femlisp{} works also without
additional software, it is reasonable to have the following libraries
available.
@itemize
@item UMFPACK or SuperLU
@item Triangle by R. M. Shewchuk.
@end itemize

@item Documentation
@itemize
@item The ANSI Common Lisp Hyperspec.  This is freely available from Xanalys.
@end itemize
@end itemize

@c ----------------------------------------------------------------

@node Quick installation , Detailed installation, Software needed, Installation
@section Quick installation

For certain operating systems, it is easy to install a Common Lisp
environment and Femlisp.

@menu
* Debian GNU/Linux::            
* Mac OS X::                    
* Minimal installation::        
@end menu

@node Debian GNU/Linux, Mac OS X, Quick installation , Quick installation
@subsection Debian GNU/Linux

The following approach should work if you are on Debian/Sarge and your
@path{/etc/apt/sources.list} file is setup to find also @emph{nonfree}
and @emph{contrib} packages:

@example
# Necessary:
apt-get install wget gnuplot dx
apt-get install cmucl cl-infix cl-asdf cl-uffi

# Recommended:
apt-get install libsuperlu3 libsuperlu3-dev
apt-get install libumfpack4 libumfpack4-dev

# Documentation (recommended)
apt-get install cmucl-doc cmucl-source hyperspec

cd ABSOLUTE_PATH_TO_DIRECTORY_OF_YOUR_CHOICE

# get Femlisp by CVS or FTP
#cvs -z3 -d:ext:anoncvs@@savannah.nongnu.org:/cvsroot/femlisp co femlisp
wget -O - http://www.femlisp.org/femlisp-current.tar.gz | tar xzvf -

cd femlisp          # change to the Femlisp directory

### At this point, you should check the paths in
### "femlisp/interface/Makefile" !

# if you have installed SuperLU and/or UMFPACK above:
make superlu        # compiles the SuperLU interface
make umfpack        # compiles the UMFPACK interface

# if you need automatic 2D triangulation:
make triangle       # gets and compiles the Triangle mesh generator

# compile Femlisp
make configure      # interactive setup
make femlisp        # compiles Femlisp and creates an executable

# we are done
make documentation  # generate the Femlisp documentation
@end example

Now you can continue as described in @ref{Setup of an interactive
environment}.

@node Mac OS X, Minimal installation, Debian GNU/Linux, Quick installation
@subsection Mac OS X

The following approach should work if you are on Mac OS X, and have
the Apple development tools, X11, and Fink installed.  Please make
sure that you have also a recent version of Emacs.

@example
apt-get install wget gnuplot dx cmucl slime

cd ABSOLUTE_PATH_TO_DIRECTORY_OF_YOUR_CHOICE

# get Femlisp by CVS or FTP
#cvs -z3 -d:ext:anoncvs@@savannah.nongnu.org:/cvsroot/femlisp co femlisp
wget -O - http://www.femlisp.org/femlisp-current.tar.gz | tar xzvf -

cd femlisp          # change to the Femlisp directory
make configure      # interactive setup
make femlisp        # creates a Femlisp executable

# we are done
make documentation  # generate the Femlisp documentation
@end example

Now you can continue as described in @ref{Emacs configuration}.

@node Minimal installation,  , Mac OS X, Quick installation
@subsection Minimal installation

The following is the minimal setup which is necessary for getting
@femlisp{} working on any architecture.  Note that it does not give
you most of the benefits of Common Lisp.  It may be sufficient,
however, to get a first impression of @femlisp{}.

We assume that you have one of CMUCL or SBCL installed, and that you
have downloaded Femlisp using either
@example
cvs -z3 -d:ext:anoncvs@@savannah.nongnu.org:/cvsroot/femlisp co femlisp
@end example
or
@example
wget -O - http://www.femlisp.org/femlisp-current.tar.gz | tar xzvf -
@end example

Then the following commands should create the executable
@path{bin/femlisp}:
@example
cd femlisp          # change to the Femlisp directory
make configure      # interactive setup
make femlisp        # compilation
@end example

It is recommendable to invoke this newly created executable either
from an Emacs shell buffer or wrapped inside the readline-wrap
@command{rlwrap} (i.e. as @code{rlwrap femlisp}).  Depending on wether
@command{dx} and @command{gnuplot} can be found on your path you will
have plotting available or not.

@c ----------------------------------------------------------------

@node Detailed installation,  , Quick installation , Installation
@section Detailed installation

@menu
* Obtaining Femlisp::           
* Installation of a CL implementation::  
* Graphics::                    
* Direct solvers::              
* Triangle mesh generator::     
* Installation of MK-DEFSYSTEM/ASDF and Infix::  
* Configuration of the startup script::  
* Compiling Femlisp::           
* Setup of an interactive environment::  
* Emacs configuration::         
@end menu

@node Obtaining Femlisp, Installation of a CL implementation, Detailed installation, Detailed installation
@subsection Obtaining Femlisp

@enumerate
@item Alternative 1: Download the current @femlisp{} version as follows
(if @command{wget} should not be available try @command{curl} instead)
@example
wget -O - http://www.femlisp.org/femlisp-current.tar.gz| tar xzvf -
@end example

You can check the correctness of the download against the binary GPG
signature in @url{http://www.femlisp.org/femlisp-current.tar.gz.sig}.
My public PGP key can be found at
@url{http://www.iwr.uni-heidelberg.de/~Nicolas.Neuss/nicolas_neuss.pgp}.

@item Alternative 2: Checkout a CVS version using the command
@example
cvs -z3 -d:ext:anoncvs@@savannah.nongnu.org:/cvsroot/femlisp co femlisp
@end example
@end enumerate

@node Installation of a CL implementation, Graphics, Obtaining Femlisp, Detailed installation
@subsection Installation of a CL implementation

There are two Common Lisp implementations with which @femlisp{} is
known to work, namely CMUCL and SBCL.  Personally, I use both.  CMUCL
behaves slightly nicer with respect to heap overflow.  On the other
hand, SBCL gives better information when generating the reference
manual.

@femlisp{} should also run with little changes with other ANSI Common
Lisp environments, especially the commercial implementations Allegro
CL and Scieneer CL.  It might also be possible to use @femlisp{} with
GCL, after some changes due to the lack of ANSI compliance of GCL.  On
the other hand, using @femlisp{} with interpreters or bytecode
compilers like CLISP does not make much sense, because such
implementations are probably much too slow.  Also using Lispworks,
Corman CL, and OpenMCL will probably be too slow, because those
implementations are to my knowledge not strong enough with respect to
fast floating point arithmetic.

@node Graphics, Direct solvers, Installation of a CL implementation, Detailed installation
@subsection Graphics

@femlisp{} uses two graphics packages, namely Gnuplot and Data
Explorer (OpenDX).  Make sure that they can be found in your path and
that they work.

@node Direct solvers, Triangle mesh generator, Graphics, Detailed installation
@subsection Direct solvers

@femlisp{} can link to two sparse direct solvers, namely SuperLU from
UMFPACK.  It is reasonable to install at least one of those as a
shared library on your system.  After you have done that, you have to
compile the glue programs superlu.c and/or umfpack.c in the directory
@path{femlisp/interface}.  This can be done by issuing the commands

@example
make superlu
@end example

or

@example
make umfpack
@end example

from within the @path{femlisp} directory.  If these commands cannot
figure out the path to the libraries, feel free to edit the Makefile
in @path{femlisp/interfaces} according to your needs.

For connecting to these libraries, @femlisp{} uses the UFFI library.
If you do not have it installed, you can install it locally by the
command

@example
make uffi
@end example

from the @path{femlisp} directory.


@node Triangle mesh generator, Installation of MK-DEFSYSTEM/ASDF and Infix, Direct solvers, Detailed installation
@subsection Triangle mesh generator

Next, Femlisp can link to the mesh generator Triangle by
J. R. Shewchuk.  If you do have it on your system, you only have to
make sure that it can be found in your path.  If not, you can download
and install it in the directory @path{femlisp/external} by issuing the
command

@example
make triangle
@end example

from withing the @path{femlisp} directory.

@node Installation of MK-DEFSYSTEM/ASDF and Infix, Configuration of the startup script, Triangle mesh generator, Detailed installation
@subsection Installation of MK-DEFSYSTEM/ASDF and Infix

First, you need a defsystem facility for using Femlisp.  Femlisp can
use both ASDF and MK-DEFSYSTEM.  Make sure that they are available
within your Common Lisp implementation.

Second, Femlisp needs the Infix library by Mark Kantrowitz.  For
convenience, a version is contained in the Femlisp distribution in the
directory @path{external}.  This version is used if Ilisp is not yet
incorporated into your Lisp.

@node Configuration of the startup script, Compiling Femlisp, Installation of MK-DEFSYSTEM/ASDF and Infix, Detailed installation
@subsection Configuration of the startup script

After these steps you should issue the command
@example
make configure
@end example
and answer the questions being asked.

@node Compiling Femlisp, Setup of an interactive environment, Configuration of the startup script, Detailed installation
@subsection Compiling Femlisp

You should now be able to start @femlisp{} by executing the script
@file{femlisp/bin/femlisp}.  The first time you use this script, your Lisp
implementation will have to compile @femlisp{} which may take a while.
The next time, startup will be much faster.  You can exit
Lisp/@femlisp{} by typing "(quit)".

You can also save a core which avoids reloading @femlisp{} during
startup.  This is done by executing the command
@example
make femlisp
@end example
After that, @femlisp{} should always start up fast.  Note that after a
change in @femlisp{} source code, this step has to be repeated.

@node Setup of an interactive environment, Emacs configuration, Compiling Femlisp, Detailed installation
@subsection Setup of an interactive environment

It is essential to use @femlisp{} from within a Lisp environment
because otherwise you do not even have a command history.  A freely
available Lisp environment is Emacs where you can use the built-in
inferior-lisp-mode, Ilisp, or SLIME.  Since inferior-lisp-mode is not
very good and Ilisp does not seem to be actively developed anymore, I
recommend using SLIME.  If you do not have it installed on your
system, you may try the command

@example
make slime
@end example

from within the @femlisp{} directory @path{femlisp}.  This will try to
download a version of SLIME in @path{femlisp/external}.

@node Emacs configuration,  , Setup of an interactive environment, Detailed installation
@subsection Emacs configuration

Finally, you should put the following lines in the file @file{.emacs}
in your home directory:

@lisp
(setq *femlisp-root* "ABSOLUTE_PATH_TO_DIRECTORY_OF_YOUR_CHOICE/femlisp/")
(add-to-list *femlisp-root* load-path)

;;; if you have installed SLIME with "make slime" in the Femlisp
;;; directoy, you will need the following line:
(add-to-list 'load-path (concat *femlisp-root* "/elisp/slime"))

(require 'slime)
(slime-setup)

(require 'femlisp)

;;; for showing the SLIME buffer if it is hidden
(defun show-repl-maybe-start-slime ()
  (interactive)
  (if (slime-connected-p)
      (slime-display-output-buffer)
      (slime)))
(global-set-key [f9] 'show-repl-maybe-start-slime)
@end lisp

Now the Emacs command @kbd{M-x femlisp} should fire up SLIME and load
@femlisp{}.  Whenever your SLIME buffer is hidden, you can bring it up
again by pressing @kbd{F9}.
