;;; -*- mode: lisp; -*-

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; mesh-defp.lisp
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Copyright (C) 2003 Nicolas Neuss, University of Heidelberg.
;;; All rights reserved.
;;; 
;;; Redistribution and use in source and binary forms, with or without
;;; modification, are permitted provided that the following conditions are
;;; met:
;;; 
;;; 1. Redistributions of source code must retain the above copyright
;;; notice, this list of conditions and the following disclaimer.
;;; 
;;; 2. Redistributions in binary form must reproduce the above copyright
;;; notice, this list of conditions and the following disclaimer in the
;;; documentation and/or other materials provided with the distribution.
;;; 
;;; THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
;;; WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
;;; MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
;;; NO EVENT SHALL THE AUTHOR, THE UNIVERSITY OF HEIDELBERG OR OTHER
;;; CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
;;; EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
;;; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;; PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;; LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;; NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defpackage "FL.MESH"
  (:use "COMMON-LISP" "FL.MACROS" "FL.UTILITIES" "FL.DEBUG"
	"FL.MATLISP" "FL.ALGEBRA" "FL.FUNCTION")
  (:export
   ;; cell.lisp
   "<CELL>" "BOUNDARY"
   "<MAPPED-CELL>" "MAPPED-P" "MAPPING" "MAPPED-CELL-CLASS"
   "DIMENSION" "MANIFOLD-DIMENSION"
   "NR-OF-SIDES" "NR-OF-VERTICES" "NR-OF-SUBCELLS"
   "FACTOR-SIMPLICES" "FACTOR-DIMENSIONS" "REFERENCE-CELL" "REFERENCE-CELL-P"
   "SUBCELLS" "VERTICES" "CORNERS"
   "CELL-MAPPING"
   "L2G" "L2DG" "L2JET" "LOCAL->GLOBAL" "LOCAL->DGLOBAL"
   "G2L" "GLOBAL->LOCAL" "GLOBAL->EMBEDDED-LOCAL"
   "INSIDE-CELL?" "LOCAL-COORDINATES-OF-MIDPOINT" "MIDPOINT"
   "<VERTEX>" "MAKE-VERTEX" "VERTEX-POSITION" "*REFERENCE-VERTEX*"
   "VERTEX?" "VERTEX-P" "PRINT-VERTEX"
   "MAKE-CELL-FROM-VERTICES" "MAKE-CELL-FROM-CORNERS"

   ;; simplex.lisp
   "<SIMPLEX>" "SIMPLEX-P" "MAKE-SIMPLEX" "MAKE-LINE"
   "*UNIT-INTERVAL*" "*UNIT-TRIANGLE*" "*UNIT-TETRAHEDRON*"
   "N-SIMPLEX"
   ;; tensorial.lisp
   "<TENSORIAL>" "*UNIT-QUADRANGLE*" "*UNIT-CUBE*" "N-CUBE" "CUBE-P"
   "CELL->CUBE" "ENSURE-TENSORIAL"
   
   ;; skeleton.lisp
   "<SKELETON>" "SKELETON" "ETABLES" "ETABLE" "SKEL-EMPTY-P"
   "SKEL-REF" "GET-CELL-PROPERTY"
   "NR-OF-CELLS" 
   "SKEL-FOR-EACH" "DOSKEL" "SKEL-MAP" "SKEL-FULL-MAP"
   "FIND-CELLS" "FIND-CELL" "FIND-CELL-FROM-POSITION" "FIND-CELL-FROM-CORNERS"
   "CELLS-OF-DIM" "ETABLE-OF-HIGHEST-DIM"
   "CELLS-OF-HIGHEST-DIM" "SURFACE-CELLS-OF-HIGHEST-DIM"
   "FOR-EACH-CELL-OF-HIGHEST-DIMENSION-ON-SURFACE"
   "MEMBER-OF-SKELETON?" "CHECK" "SKELETON-BOUNDARY"
   "REFCELL-SKELETON" "SUBSKELETON"

   ;; identify
   "IDENTIFIED" "IDENTIFIED-P"
   "BOUNDARY-IDENTIFICATIONS" "COMBINE-IDENTIFICATIONS"
   "ITERATE-IDENTIFICATIONS" "IDENTIFY" 
   "IDENTIFY-UNIT-CELL-FACES"
   
   ;; skeleton-build.lisp
   "SKELETON-WITHOUT-CELL" "SKEL-ADD!" "COPY-SKELETON"
   "TRANSFORMED-SKELETON" "LINEARLY-TRANSFORMED-SKELETON" "SHIFT-SKELETON"
   "TELESCOPE" "REFINED-SKELETON-COPY" "STRUCTURED-SKELETON"
   
   ;; refine.lisp
   "CHILDREN" "PARENT" "REFINED-P"
   "REFINE-INFO" "SKELETON-REFINEMENT" "INITIALIZE-REFINED-SKELETON"
   "REFINE-GLOBALLY" "INVERT-REFINEMENT"
   "SUBCELL-CHILDREN" "REFCELL-CHILDREN" "INNER-REFCELL-CHILDREN"
   "NR-OF-SUBCELL-CHILDREN" 
   "REFCELL-REFINEMENT-SKELETON" "REFCELL-REFINEMENT-INDEX-TABLE"
   "REFCELL-REFINEMENT-VERTICES" "NR-OF-REFINEMENT-VERTICES"

   ;; domain.lisp
   "<DOMAIN>" "DOMAIN-BOUNDARY" "DOMAIN-CHARACTERISTICS" "EXTENSIBLE-P"
   "MAKE-DOMAIN"
   "N-SIMPLEX-DOMAIN" "TENSORIAL-DOMAIN" "N-CUBE-DOMAIN"
   "BOX-DOMAIN" "N-CELL-DOMAIN" "N-BALL-DOMAIN"
   "*UNIT-INTERVAL-DOMAIN*" "*UNIT-TRIANGLE-DOMAIN*" "*UNIT-TETRAHEDRON-DOMAIN*"
   "*UNIT-QUADRANGLE-DOMAIN*" "*UNIT-CUBE-DOMAIN*"
   "*CIRCLE-DOMAIN*" "TRIANGLE-DOMAIN" "L-DOMAIN"

   ;; mesh.lisp
   "<MESH>" "DOMAIN"
   "PATCH" "PATCH-OF-CELL" "CELL-IDENTIFICATION"
   "REFINE" "<HIERARCHICAL-MESH>" "MESHES" "REFINEMENTS" "ACCUMULATED-MESH"
   "NR-OF-LEVELS" "CELLS-ON-LEVEL" "TOP-LEVEL" "BOTTOM-LEVEL-CELLS" "TOP-LEVEL-CELLS"
   "SURFACE-CELLS-OF-DIM" "NR-OF-SURFACE-CELLS"
   "MESH->HIERARCHICAL-MESH" "REFINE-HIERARCHICAL-MESH"
   "REFINEMENT-INTERFACE" "HIERARCHICALLY-ORDERED-CELLS"
   
   ;; meshgen.lisp
   "MAKE-MESH-FROM-DOMAIN" "COPY-MESH" "UNIFORMLY-REFINED-MESH"
   "INSERT-CELL-FROM-CORNERS" "SPECIAL-MESH-ON-BOX-DOMAIN"
   "UNIFORM-MESH-ON-BOX-DOMAIN"
   
   "MAKE-HIERARCHICAL-MESH-FROM-DOMAIN" "MAKE-HIERARCHICAL-MESH-FROM-DOMAIN"
   "UNIFORMLY-REFINED-HIERARCHICAL-MESH"
   "COMPARE-LEXICOGRAPHICALLY" "SORT-LEXICOGRAPHICALLY"
   "TRIANGULIZE"
   
   ;; extend.lisp
   "EXTENSION" "EXTEND" "STANDARD-EXTENDER" "CUBE-EXTENDER"
   )
  (:documentation "This package provides the definition of cells, clusters
of cells called (<skeleton>), domains and meshes as well as routines for
handling those objects."))
